---
- name: Send CFE Declaration 
  hosts: "{{ bigip }}" 
  gather_facts: no

  tasks:
  - name: Wait until the pair of BIG-IP is In Sync Mode
    raw: "run /util bash -c 'cat /var/prompt/cmiSyncStatus'"
    until: (result_ready.stdout.find("In Sync") != -1)
    register: result_ready
    retries: 60
    delay: 10
    ignore_errors: yes

  - name: Result Ready Output
    debug:
      var: result_ready

  - name: Send CFE Declaration to BIGIP 
    template:
      src: "CFE_Template.j2"
      dest: "CFE_{{ host }}.json"
    delegate_to: 127.0.0.1

  - name: Send declaration
    uri:
      url: "https://{{ bigip }}/mgmt/shared/cloud-failover/declare"
      method: POST
      user: "{{ user }}"
      password: "{{ password }}"
      body: "{{ lookup('file','CFE_{{ host }}.json') }}"
      status_code: 200
      timeout: 300
      body_format: json
      validate_certs: no
    register: result_cfe
    delegate_to: 127.0.0.1

  - name: Result CFE Declarartion
    debug:
      var: result_cfe

